version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  backend:
    build: ./backend-go/
    container_name: go-backend
    image: backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  frontend:
    build: ./frontend-reactjs/react-frontend/
    container_name: react-frontend
    image: frontend  
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:

